import React, { useState } from 'react';
import { X, Database, Copy, Check } from 'lucide-react';

const SqlSidebar = ({ isOpen, setIsOpen, sql }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!sql) return;
    try {
      await navigator.clipboard.writeText(sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = sql;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div 
      className={`h-full bg-slate-900/60 backdrop-blur-2xl border-l border-white/5 transition-all duration-500 ease-in-out flex flex-col overflow-hidden z-[100] ${
        isOpen ? 'w-[320px]' : 'w-0 border-l-0'
      }`}
    >
      {/* Header */}
      <div className="p-4 border-b border-white/5 flex items-center justify-between bg-black/20">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-clinical-blue/10 rounded-lg border border-clinical-blue/20">
            <Database size={16} className="text-clinical-blue" />
          </div>
          <div>
            <h3 className="text-[11px] font-bold text-white uppercase tracking-[0.2em]">SQL Query</h3>
            <p className="text-[9px] text-gray-600 font-semibold tracking-tight uppercase">Generated SQL</p>
          </div>
        </div>
        <button 
          onClick={() => setIsOpen(false)}
          className="p-1.5 hover:bg-white/5 rounded-full transition-all text-gray-600 hover:text-white"
        >
          <X size={16} />
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-5 custom-scrollbar">
        {sql ? (
          <div className="animate-fade-in flex flex-col h-full">
            <div className="flex-1 flex flex-col">
              <div className="flex items-center justify-between mb-4">
                <span className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.2em]">Query</span>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-[9px] font-bold uppercase tracking-widest border transition-all bg-white/5 border-white/10 text-gray-400 hover:border-clinical-blue/40 hover:text-clinical-blue"
                >
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
              </div>
              <div className="bg-black/40 rounded-xl border border-white/10 p-5 overflow-x-auto shadow-inner">
                <pre className="text-[12px] leading-relaxed text-clinical-lime font-mono whitespace-pre-wrap break-all">
                  {sql}
                </pre>
              </div>
            </div>
            <div className="mt-6 flex items-start gap-3 p-4 bg-white/5 rounded-xl border border-white/10 shadow-inner">
              <Database size={14} className="text-clinical-blue/40 mt-0.5 shrink-0" />
              <p className="text-[10px] text-gray-500 font-medium leading-relaxed italic">
                This SQL was generated by the clinical intelligence agent and executed against the local database to retrieve the query results.
              </p>
            </div>
          </div>
        ) : (
          <div className="h-full flex flex-col items-center justify-center text-center p-8 space-y-4">
            <div className="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center border border-white/5">
              <Database size={28} className="text-gray-700" />
            </div>
            <p className="text-[12px] text-gray-500 font-bold uppercase tracking-widest">No SQL Query</p>
            <p className="text-[11px] text-gray-600 max-w-[200px]">This trace did not generate any SQL query.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default SqlSidebar;
