"""Update vector dimension to 1024

Revision ID: 0b564e3795d0
Revises: cc88df186602
Create Date: 2026-04-10 13:00:15.321400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0b564e3795d0'
down_revision: Union[str, None] = 'cc88df186602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_notes', 'vector',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_notes', 'vector',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
