"""change_dob_to_date_type

Revision ID: 46c1dba26128
Revises: 0b564e3795d0
Create Date: 2026-04-11 12:44:42.877235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c1dba26128'
down_revision: Union[str, None] = '0b564e3795d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='date_of_birth::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='date_of_birth::varchar')
    # ### end Alembic commands ###
