"""add_analytics_columns

Revision ID: 969581938117
Revises: 46c1dba26128
Create Date: 2026-04-12 00:11:38.110900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969581938117'
down_revision: Union[str, None] = '46c1dba26128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('operating_budget', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('risk_profile', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'risk_profile')
    op.drop_column('departments', 'operating_budget')
    # ### end Alembic commands ###
