"""add_staff_salary_and_supply_unit_cost

Revision ID: d1acaed3df10
Revises: 969581938117
Create Date: 2026-04-22 00:10:58.079179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1acaed3df10'
down_revision: Union[str, None] = '969581938117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_supplies', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.add_column('staff', sa.Column('salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'salary')
    op.drop_column('medical_supplies', 'unit_cost')
    # ### end Alembic commands ###
