"""add_semantic_query_cache

Revision ID: d40d328ddad8
Revises: e7b9a5c8d2f1
Create Date: 2026-05-20 19:40:20.983724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd40d328ddad8'
down_revision: Union[str, None] = 'e7b9a5c8d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_query_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=1024), nullable=False),
    sa.Column('cached_sql', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_query_cache_query_text'), 'semantic_query_cache', ['query_text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_query_cache_query_text'), table_name='semantic_query_cache')
    op.drop_table('semantic_query_cache')
    # ### end Alembic commands ###
